# Generated by Django 3.0.3 on 2020-03-11 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=64, verbose_name='first')),
                ('last_name', models.CharField(max_length=64, verbose_name='last')),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('manager', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('stakeholder', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Applicant', 'Applicant'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('Stakeholder', 'Stakeholder'), ('Administrator', 'Administrator')], default='Applicant', max_length=16)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1056, null=True)),
                ('members', models.ManyToManyField(to='rest_api.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256, null=True)),
                ('key', models.CharField(blank=True, max_length=1024)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 11, 19, 17, 43, 316619))),
                ('active', models.BooleanField(default=True)),
                ('internal_only', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Committee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address')),
                ('companies', models.ManyToManyField(to='rest_api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=8)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Applicant')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Listing')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Company'),
        ),
    ]
