# Generated by Django 3.0.5 on 2020-04-15 20:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1056, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='first')),
                ('last_name', models.CharField(max_length=64, verbose_name='last')),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('manager', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('stakeholder', models.BooleanField(default=False)),
                ('bio', models.CharField(max_length=1024, null=True)),
                ('skills', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Applicant', 'Applicant'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('Stakeholder', 'Stakeholder'), ('Administrator', 'Administrator')], default='Applicants', max_length=16)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 20, 33, 7, 895219), null=True)),
                ('active', models.BooleanField(default=True)),
                ('internal_only', models.BooleanField(default=False)),
                ('key_words', models.TextField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Committee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Company')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Company'),
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(to='rest_api.Profile'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address')),
                ('companies', models.ManyToManyField(to='rest_api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=8)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[(1, 'Optimal Candidate'), (2, 'Considerable Candidate'), (3, 'Standard Candidate')], default=3)),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Profile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Listing')),
            ],
        ),
    ]
