# Generated by Django 3.0.4 on 2020-03-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('Stakeholder', 'Stakeholder'), ('Administrator', 'Administrator')], default='ApplicantS', max_length=16),
        ),
    ]
