# Generated by Django 3.0.3 on 2020-03-10 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='type',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('Stakeholder', 'Stakeholder'), ('Administrator', 'Administrator')], default='Applicant', max_length=16),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 17, 42, 10, 643003)),
        ),
    ]
