# Generated by Django 3.0.3 on 2020-03-10 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200310_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.AddField(
            model_name='applicant',
            name='password',
            field=models.CharField(default='superroot', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(default='root', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 20, 31, 27, 517622)),
        ),
    ]
