# Generated by Django 3.0.5 on 2020-04-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200328_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='key',
        ),
        migrations.AddField(
            model_name='listing',
            name='key_words',
            field=models.TextField(default='python, javascript'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
