# Generated by Django 3.0.5 on 2020-04-19 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200418_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 20, 0, 9, 0, 941807), null=True),
        ),
    ]
