# Generated by Django 3.0.5 on 2020-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20200413_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
