# Generated by Django 3.0.3 on 2020-03-09 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200309_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='company',
        ),
        migrations.AddField(
            model_name='association',
            name='company',
            field=models.ManyToManyField(to='rest_api.Company'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 0, 42, 8, 913601)),
        ),
    ]
