# Generated by Django 3.0.5 on 2020-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_application_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
