# Generated by Django 3.0.5 on 2020-04-21 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200420_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 1, 2, 37, 787676), null=True),
        ),
    ]
