# Generated by Django 3.0.3 on 2020-03-09 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200309_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='company',
            new_name='companies',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 0, 42, 32, 450576)),
        ),
    ]
