# Generated by Django 3.0.5 on 2020-04-15 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200415_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 17, 30, 5, 857501), null=True),
        ),
    ]
