# Generated by Django 3.0.3 on 2020-03-09 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20200309_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='appicant',
            new_name='applicant',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 0, 46, 23, 734691)),
        ),
    ]
