# Generated by Django 3.0.3 on 2020-03-09 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_auto_20200309_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicants',
        ),
        migrations.AddField(
            model_name='application',
            name='applicants',
            field=models.ManyToManyField(to='rest_api.Applicant'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 5, 25, 3, 434339)),
        ),
    ]
