export default {
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_ERROR: "FETCH_USERS_ERROR",
  FETCH_DATA_REQUEST: "FETCH_ALL_DATA_REQUEST",
  FETCH_DATA_SUCCESS: "FETCH_ALL_DATA_SUCCESS",
  FETCH_DATA_ERROR: "FETCH_ALL_DATA_ERROR",
  FETCH_MAIN_PROFILE_REQUEST: "FETCH_MAIN_PROFILE_REQUEST",
  FETCH_MAIN_PROFILE_SUCCESS: "FETCH_MAIN_PROFILE_SUCCESS",
  FETCH_MAIN_PROFILE_ERROR: "FETCH_MAIN_PROFILE_ERROR",
  FETCH_PROFILE_REQUEST: "FETCH_PROFILE_REQUEST",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_ERROR: "FETCH_PROFILE_ERROR"
}